### PR TITLE
Add a helper function for configuring all contour properties in one step

### PR DESCRIPTION
**Pull request by confluence**
Implements #62.

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
this is great, handy, and intuitive. 👍

**Comment by confluence** [comment]
I've realised that I haven't been consistent in mentioning default values in the function docstring (this was carried over from the original individual functions). I'd like to fix this before merging.

What are the units for the smoothing factor -- pixels? Does it depend on the smoothing mode?

**Comment by kswang1029** [comment]
> I've realised that I haven't been consistent in mentioning default values in the function docstring (this was carried over from the original individual functions). I'd like to fix this before merging.
> 
> What are the units for the smoothing factor -- pixels? Does it depend on the smoothing mode?

It is in pixel as the kernel size. It is for Gaussian and box smoothing.

**Comment by kswang1029** [comment]
> > I've realised that I haven't been consistent in mentioning default values in the function docstring (this was carried over from the original individual functions). I'd like to fix this before merging.
> > What are the units for the smoothing factor -- pixels? Does it depend on the smoothing mode?
> 
> It is in pixel as the kernel size. It is for Gaussian and box smoothing.


> > I've realised that I haven't been consistent in mentioning default values in the function docstring (this was carried over from the original individual functions). I'd like to fix this before merging.
> > What are the units for the smoothing factor -- pixels? Does it depend on the smoothing mode?
> 
> It is in pixel as the kernel size. It is for Gaussian and box smoothing.

Uh just realized that IIRC some parameters can be customized in the preferences so we need to consider this in the docstring🤔

**Comment by confluence** [comment]
Ah, if the default is configurable in the preferences then I think I should rewrite these functions not to hardcode a default. There are probably a few other functions like that.

**Comment by kswang1029** [comment]
> Ah, if the default is configurable in the preferences then I think I should rewrite these functions not to hardcode a default. There are probably a few other functions like that.

Guess we need a preferences class to store all user defaults then we can refer it elsewhere in the codebase?

**Comment by confluence** [comment]
> Guess we need a preferences class to store all user defaults then we can refer it elsewhere in the codebase?

It should be possible to write these functions in such a way that the frontend's default is used if the user doesn't specify a value, and the wrapper doesn't need to be aware of the default. I think that in some places I copied a default from the frontend, assuming that it was hardcoded there, but even for defaults that are hardcoded we should avoid doing this (because then they can get out of sync, and have to be maintained in two places). There are some exceptions which are unlikely to change and are probably fine.

I'm pretty sure that in cases where the same action is used to set multiple values (and the function calling that action needs to supply all the parameters), we can use the existing macro functionality in the wrapper to refer to values set in the frontend without ever specifying the literal values. I discussed this with @I-Chenn yesterday because it came up in the vector overlay PR; we still need to check the solution to make 100% sure that it works. I'll have a closer look at this on Monday.

**Comment by confluence** [comment]
@kswang1029 I have modified the functions so that all of `levels`, `smoothing_mode` and `smoothing_factor` are optional. This means that we avoid hardcoding defaults which can be changed in the frontend, and also that we can now specify only one or two of the three both in `configure_contours` and in `plot_contours`. The others default to the current frontend value. This is more consistent with the way that the style properties work.

I have noticed a discrepancy in the behaviour of various parts of this configuration in the UI. The style properties (dash and colour) are updated in the displayed image immediately when their respective actions are called, *and* the changed values are visible in the GUI contour dialog. However, the levels and smoothing options are only updated in the image when the action to apply contours is called (something which we can mitigate in the wrapper) *and* the changed values are *never* visible in the GUI dialog (which may be confusing to the user). I don't know how much of a problem the latter is. This is frontend behaviour (those sections of the dialog do not seem to detect when the underlying values have changed in the same way as the style section does), so it would need to be addressed in the frontend.

I am considering whether we should always call the `applyContours` action from the `configure_contours` method and remove the separate `apply_contours` method. Now that we have `plot_contours`, perhaps it's fine to keep the more fine-grained methods as they are -- but this makes the behaviour of the levels and smoothing options inconsistent with the behaviour of the style options. Do you have a preference?

**Comment by kswang1029** [comment]
> @kswang1029 I have modified the functions so that all of `levels`, `smoothing_mode` and `smoothing_factor` are optional. This means that we avoid hardcoding defaults which can be changed in the frontend, and also that we can now specify only one or two of the three both in `configure_contours` and in `plot_contours`. The others default to the current frontend value. This is more consistent with the way that the style properties work.
> 
> I have noticed a discrepancy in the behaviour of various parts of this configuration in the UI. The style properties (dash and colour) are updated in the displayed image immediately when their respective actions are called, _and_ the changed values are visible in the GUI contour dialog. However, the levels and smoothing options are only updated in the image when the action to apply contours is called (something which we can mitigate in the wrapper) _and_ the changed values are _never_ visible in the GUI dialog (which may be confusing to the user). I don't know how much of a problem the latter is. This is frontend behaviour (those sections of the dialog do not seem to detect when the underlying values have changed in the same way as the style section does), so it would need to be addressed in the frontend.
> 
> I am considering whether we should always call the `applyContours` action from the `configure_contours` method and remove the separate `apply_contours` method. Now that we have `plot_contours`, perhaps it's fine to keep the more fine-grained methods as they are -- but this makes the behaviour of the levels and smoothing options inconsistent with the behaviour of the style options. Do you have a preference?

I feel having high level functions is sufficient based on the general use cases. The inconsistency in “apply” is due to that the responsible end is different. Changing contour color/thickness is using WebGL so it is pure frontend and it is sensible to see the results immediately (GPU does the job very fast). Smoothing method however involves the backend for image smoothing before calculating contour vertices. I think it’s okay to have such “inconsistencies” even in the python interface. Mostly I think users will use high level function directly.

**Comment by confluence** [comment]
OK, great. In that case, I'm going to merge this -- I tested the optional parameters at my end and they seem to be working as expected.

**Pull request merged**
